name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "True"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TITLE: "True"
          COMMIT_MESSAGE: Updated the Readme
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
